//! Phase-3 GPU/NPU backend: lower data-parallel EIR kernels to **WGSL** compute
//! shaders.
//!
//! Scope: straight-line, world-access-free functions (a "map" kernel: one input
//! value in, one result out), i.e. the per-element arithmetic that dominates
//! field solvers and particle updates. Functions with component access, calls,
//! branches, effects, or spatial/field queries are ineligible and stay on the
//! CPU backend.
//!
//! **Semantics.** WebGPU's shading language has no `f64` (and most devices lack
//! the `shader-f64` feature), so a WGSL kernel computes in **f32**. This backend
//! is therefore an **approximate device backend**, not a bit-exact one: it MUST
//! NOT be substituted for the interpreter where exact f64 semantics matter. The
//! emitter is verified two ways (see tests): a dependency-free structural
//! validator checks the shader is well-formed, and a CPU f32 oracle (the same
//! lowering evaluated on the CPU) is checked against the interpreter within f32
//! tolerance. `naga` validation is added as a dev-dependency where available.
//!
//! This module emits shader source; it does not create a GPU device. Wiring it
//! to a WebGPU host (and the RFC-0027 lifecycle) is a separate integration.

use crate::eir::{EirModule, Function, Immediate, Opcode};
use pwe_api::{Error, Result, Status};

/// The `target` value selecting the WGSL device backend at the AOT boundary.
pub const WGSL_TARGET: u16 = 4;

fn error(status: Status, detail: u32) -> Error {
    Error {
        status,
        detail,
        byte_offset: 0,
    }
}

/// Whether a function can be lowered to a WGSL map kernel.
pub fn eligible(f: &Function) -> bool {
    if f.argument_count != 1 {
        return false;
    }
    f.instructions.iter().all(|i| {
        i.target.is_none()
            && matches!(
                i.opcode,
                Opcode::Nop
                    | Opcode::Const
                    | Opcode::Add
                    | Opcode::Sub
                    | Opcode::Mul
                    | Opcode::Div
                    | Opcode::Rem
                    | Opcode::Pow
                    | Opcode::Fma
                    | Opcode::Eq
                    | Opcode::Ne
                    | Opcode::Lt
                    | Opcode::Le
                    | Opcode::Gt
                    | Opcode::Ge
                    | Opcode::Select
                    | Opcode::Sin
                    | Opcode::Cos
                    | Opcode::Exp
                    | Opcode::Ln
                    | Opcode::Sqrt
                    | Opcode::Abs
                    | Opcode::Floor
                    | Opcode::Ceil
                    | Opcode::Round
                    | Opcode::Sign
                    | Opcode::Log10
                    | Opcode::Log2
                    | Opcode::Sinh
                    | Opcode::Cosh
                    | Opcode::Tanh
                    | Opcode::Asin
                    | Opcode::Acos
                    | Opcode::Atan
                    | Opcode::Atan2
                    | Opcode::Hypot
                    | Opcode::Return
            )
    })
}

/// Emits a WGSL compute shader that applies function `func_id` element-wise to
/// an `f32` input buffer, writing an `f32` output buffer.
pub fn emit_compute_shader(module: &EirModule, func_id: u64) -> Result<String> {
    let f = module
        .functions
        .iter()
        .find(|f| f.id == func_id)
        .ok_or_else(|| error(Status::Invalid, 5))?;
    if !eligible(f) {
        return Err(error(Status::Invalid, 5));
    }
    let cap = f
        .instructions
        .iter()
        .map(|i| i.result_id as usize + 1)
        .max()
        .unwrap_or(2)
        .max(f.instructions.len())
        .max(2);
    let mut body = String::new();
    body.push_str("  let i = gid.x;\n");
    body.push_str("  if (i >= arrayLength(&output)) { return; }\n");
    body.push_str(&format!("  var r: array<f32, {cap}>;\n"));
    // Parameters arrive in registers 1.. (EIR CALL convention); a map kernel has
    // exactly one input.
    body.push_str("  r[1] = input[i];\n");
    for ins in &f.instructions {
        body.push_str(&emit_instruction(ins)?);
    }
    // The return value is the last `Return` operand.
    let ret = f
        .instructions
        .iter()
        .rev()
        .find(|i| i.opcode == Opcode::Return)
        .and_then(|i| i.operands.first().copied())
        .unwrap_or(0);
    body.push_str(&format!("  output[i] = r[{ret}];\n"));

    Ok(format!(
        "// Generated by pwe (WGSL device backend, target {WGSL_TARGET}).\n\
         // f32 approximation of a 64-bit-float EIR kernel - not bit-exact.\n\
         @group(0) @binding(0) var<storage, read> input: array<f32>;\n\
         @group(0) @binding(1) var<storage, read_write> output: array<f32>;\n\
         @compute @workgroup_size(64)\n\
         fn main(@builtin(global_invocation_id) gid: vec3<u32>) {{\n{body}}}\n"
    ))
}

fn const_f32(imm: Immediate) -> f32 {
    match imm {
        Immediate::I32(v) => v as f32,
        Immediate::U32(v) => v as f32,
        Immediate::I64(v) => v as f32,
        Immediate::U64(v) => v as f32,
        Immediate::F32(v) => v,
        Immediate::F64(v) => v as f32,
        Immediate::Bool(v) => u8::from(v) as f32,
    }
}

fn lit(v: f32) -> String {
    if v.is_nan() {
        // WGSL has no NaN literal; produce it portably at f32 width.
        "(0.0 / 0.0)".to_string()
    } else if v.is_infinite() {
        if v > 0.0 {
            "(1.0 / 0.0)".to_string()
        } else {
            "(-1.0 / 0.0)".to_string()
        }
    } else {
        format!("{v:?}f")
    }
}

fn bin_op(op: Opcode) -> Option<&'static str> {
    Some(match op {
        Opcode::Add => "+",
        Opcode::Sub => "-",
        Opcode::Mul => "*",
        Opcode::Div => "/",
        Opcode::Rem => "%",
        _ => return None,
    })
}

fn cmp_op(op: Opcode) -> Option<&'static str> {
    Some(match op {
        Opcode::Eq => "==",
        Opcode::Ne => "!=",
        Opcode::Lt => "<",
        Opcode::Le => "<=",
        Opcode::Gt => ">",
        Opcode::Ge => ">=",
        _ => return None,
    })
}

fn unary_fn(op: Opcode) -> Option<&'static str> {
    Some(match op {
        Opcode::Sin => "sin",
        Opcode::Cos => "cos",
        Opcode::Exp => "exp",
        Opcode::Ln => "log",
        Opcode::Sqrt => "sqrt",
        Opcode::Abs => "abs",
        Opcode::Floor => "floor",
        Opcode::Ceil => "ceil",
        Opcode::Round => "round",
        Opcode::Sign => "sign",
        Opcode::Log10 => return None, // emulated below
        Opcode::Log2 => "log2",
        Opcode::Sinh => "sinh",
        Opcode::Cosh => "cosh",
        Opcode::Tanh => "tanh",
        Opcode::Asin => "asin",
        Opcode::Acos => "acos",
        Opcode::Atan => "atan",
        _ => return None,
    })
}

fn emit_instruction(ins: &crate::eir::Instruction) -> Result<String> {
    let o = &ins.operands;
    let res = ins.result_id;
    let line = match ins.opcode {
        Opcode::Nop => String::new(),
        Opcode::Const => format!(
            "  r[{res}] = {};\n",
            lit(const_f32(ins.constant.unwrap_or(Immediate::F32(0.0))))
        ),
        Opcode::Fma => format!("  r[{res}] = fma(r[{}], r[{}], r[{}]);\n", o[0], o[1], o[2]),
        Opcode::Pow => format!("  r[{res}] = pow(r[{}], r[{}]);\n", o[0], o[1]),
        Opcode::Atan2 => format!("  r[{res}] = atan2(r[{}], r[{}]);\n", o[0], o[1]),
        Opcode::Hypot => format!("  r[{res}] = hypot(r[{}], r[{}]);\n", o[0], o[1]),
        Opcode::Log10 => format!("  r[{res}] = log(r[{}]) / log(10.0f);\n", o[0]),
        Opcode::Log2 => format!("  r[{res}] = log2(r[{}]);\n", o[0]),
        Opcode::Select => format!(
            "  r[{res}] = select(r[{}], r[{}], r[{}] != 0.0f);\n",
            o[2], o[1], o[0]
        ),
        Opcode::Return => String::new(),
        op if bin_op(op).is_some() => format!(
            "  r[{res}] = r[{}] {} r[{}];\n",
            o[0],
            bin_op(op).unwrap_or("+"),
            o[1]
        ),
        op if cmp_op(op).is_some() => format!(
            "  r[{res}] = select(0.0f, 1.0f, r[{}] {} r[{}]);\n",
            o[0],
            cmp_op(op).unwrap_or("=="),
            o[1]
        ),
        op if unary_fn(op).is_some() => {
            format!(
                "  r[{res}] = {}(r[{}]);\n",
                unary_fn(op).unwrap_or("abs"),
                o[0]
            )
        }
        _ => return Err(error(Status::Invalid, 5)),
    };
    Ok(line)
}

/// Dependency-free structural validation of a generated WGSL shader: balanced
/// delimiters, a `main` entry point with `@compute`/`@workgroup_size`, the
/// storage bindings it references, and no `f64` (the device backend is f32).
pub fn validate_shader(source: &str) -> Result<()> {
    let mut depth: i32 = 0;
    for ch in source.chars() {
        match ch {
            '{' | '(' | '[' => depth += 1,
            '}' | ')' | ']' => {
                depth -= 1;
                if depth < 0 {
                    return Err(error(Status::Invalid, 6));
                }
            }
            _ => {}
        }
    }
    if depth != 0 {
        return Err(error(Status::Invalid, 6));
    }
    for needle in [
        "@compute",
        "@workgroup_size",
        "fn main(",
        "var<storage, read> input",
        "arrayLength(&output)",
    ] {
        if !source.contains(needle) {
            return Err(error(Status::Invalid, 6));
        }
    }
    if source.contains("f64") {
        return Err(error(Status::Invalid, 6));
    }
    Ok(())
}

/// A CPU oracle: evaluates a WGSL-eligible EIR function in **f32** the same way
/// the emitted shader does. Used to check the lowering matches the interpreter
/// within f32 tolerance.
pub fn eval_f32(module: &EirModule, func_id: u64, input: f32) -> Result<f32> {
    let f = module
        .functions
        .iter()
        .find(|f| f.id == func_id)
        .ok_or_else(|| error(Status::Invalid, 5))?;
    if !eligible(f) {
        return Err(error(Status::Invalid, 5));
    }
    let cap = f
        .instructions
        .iter()
        .map(|i| i.result_id as usize + 1)
        .max()
        .unwrap_or(2)
        .max(2);
    let mut r: Vec<f32> = vec![0.0; cap];
    r[1] = input;
    for ins in &f.instructions {
        let o = &ins.operands;
        let get = |k: usize| r[o[k] as usize];
        let v = match ins.opcode {
            Opcode::Nop | Opcode::Return => continue,
            Opcode::Const => const_f32(ins.constant.unwrap_or(Immediate::F32(0.0))),
            Opcode::Fma => get(0) * get(1) + get(2),
            Opcode::Pow => get(0).powf(get(1)),
            Opcode::Atan2 => get(0).atan2(get(1)),
            Opcode::Hypot => get(0).hypot(get(1)),
            Opcode::Log10 => get(0).log10(),
            Opcode::Select => {
                if get(0) != 0.0 {
                    get(1)
                } else {
                    get(2)
                }
            }
            Opcode::Add => get(0) + get(1),
            Opcode::Sub => get(0) - get(1),
            Opcode::Mul => get(0) * get(1),
            Opcode::Div => get(0) / get(1),
            Opcode::Rem => get(0) % get(1),
            Opcode::Eq => f32::from(get(0) == get(1)),
            Opcode::Ne => f32::from(get(0) != get(1)),
            Opcode::Lt => f32::from(get(0) < get(1)),
            Opcode::Le => f32::from(get(0) <= get(1)),
            Opcode::Gt => f32::from(get(0) > get(1)),
            Opcode::Ge => f32::from(get(0) >= get(1)),
            Opcode::Sin => get(0).sin(),
            Opcode::Cos => get(0).cos(),
            Opcode::Exp => get(0).exp(),
            Opcode::Ln => get(0).ln(),
            Opcode::Sqrt => get(0).sqrt(),
            Opcode::Abs => get(0).abs(),
            Opcode::Floor => get(0).floor(),
            Opcode::Ceil => get(0).ceil(),
            Opcode::Round => get(0).round(),
            Opcode::Sign => get(0).signum(),
            Opcode::Log2 => get(0).log2(),
            Opcode::Sinh => get(0).sinh(),
            Opcode::Cosh => get(0).cosh(),
            Opcode::Tanh => get(0).tanh(),
            Opcode::Asin => get(0).asin(),
            Opcode::Acos => get(0).acos(),
            Opcode::Atan => get(0).atan(),
            _ => return Err(error(Status::Invalid, 5)),
        };
        r[ins.result_id as usize] = v;
    }
    let ret = f
        .instructions
        .iter()
        .rev()
        .find(|i| i.opcode == Opcode::Return)
        .and_then(|i| i.operands.first().copied())
        .unwrap_or(0);
    Ok(r[ret as usize])
}

#[cfg(test)]
fn f32_from(v: f64) -> f32 {
    v as f32
}

#[cfg(test)]
mod tests {
    use super::*;

    fn eir_of(src: &str) -> EirModule {
        // Emit from the optimized EIR (so Mul/Add has already fused to Fma).
        let parsed = crate::lang::parse(src).unwrap();
        crate::lang::compile_program(parsed).unwrap().eir.optimize()
    }

    #[test]
    fn emits_and_validates_a_compute_shader() {
        let src = "world { gravity=(0,0,0) entity e { state=(a=0.0, x=0.0) } } \
                   funcs { f(a) { a * a + sin(a) } } \
                   systems { update { on=e; dt=1.0  x = f(a) } }";
        let module = eir_of(src);
        let shader = emit_compute_shader(&module, 0xF000_0000).unwrap();
        validate_shader(&shader).unwrap();
        assert!(shader.contains("fma("), "Mul/Add should fuse to fma");
        assert!(shader.contains("sin("));
        assert!(shader.contains("output[i] = r["));
    }

    #[test]
    fn rejects_ineligible_functions() {
        let src = "world { gravity=(0,0,0) entity e { state=(a=0.0, x=0.0) } } \
                   funcs { f(a) { a / 0.0 + a } } \
                   systems { update { on=e; dt=1.0  x = f(a) } }";
        let _ = eir_of(src);
        // The system `update` function reads/writes the world -> ineligible.
        let module = eir_of(src);
        let sys_fn = module
            .functions
            .iter()
            .find(|f| f.argument_count == 0)
            .unwrap();
        assert!(!eligible(sys_fn));
        assert!(emit_compute_shader(&module, sys_fn.id).is_err());
    }

    #[test]
    fn f32_oracle_tracks_the_interpreter_within_tolerance() {
        // The device backend is f32; compare its oracle to the f64 interpreter
        // and require f32-level agreement.
        let src = "world { gravity=(0,0,0) entity e { state=(a=0.0, x=0.0) } } \
                   funcs { f(a) { a * a + sin(a) } } \
                   systems { update { on=e; dt=1.0  x = f(a) } }";
        let module = eir_of(src);
        let mut rt = crate::lang::LangRuntime::compile(src).unwrap();
        let id = 0xF000_0000u64;
        for i in 0..32 {
            let a = i as f64 * 0.4 - 6.0;
            rt.scene
                .get_mut(pwe_api::EntityId(1))
                .unwrap()
                .state
                .as_mut()
                .unwrap()
                .values[0] = a;
            rt.step_jit().unwrap();
            let interp = rt
                .scene
                .get(pwe_api::EntityId(1))
                .unwrap()
                .state
                .as_ref()
                .unwrap()
                .values[1];
            let oracle = eval_f32(&module, id, f32_from(a)).unwrap();
            let expect = f32_from(interp);
            let tol = 1e-4 * expect.abs().max(1.0);
            assert!(
                (oracle - expect).abs() <= tol,
                "at a={a}: interpreter f32={expect} oracle={oracle}"
            );
        }
    }
}
