/* pwe_abi.h — PWE v0.2 C11 ABI (RFC-0026, RFC-0031).
 *
 * Generated to match `pwe_api::ffi` (Rust #[repr(C)]). Every exported function
 * is `PweStatus fn(void* user, ..., PweError*)`; buffers are
 * `(const uint8_t* ptr, uint64_t len)`; output ownership is returned only by
 * `runtime_free`. Callers require major equality and `size` covering each used
 * slot; unknown tail slots are ignored.
 *
 * Do not edit this file by hand; it is locked to the Rust layouts by
 * `ffi::tests::*_layout_matches_c_header` in `src/ffi.rs`.
 */
#ifndef PWE_ABI_H
#define PWE_ABI_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PWE_ABI_MAJOR 2
#define PWE_ABI_MINOR 0

typedef uint32_t PweStatus;

#define PWE_OK 0u          /* OK */
#define PWE_INVALID 1u     /* INVALID */
#define PWE_LIMIT 2u       /* LIMIT */
#define PWE_SCHEMA_HASH 3u /* SCHEMA_HASH */
#define PWE_SCHEMA_UNSUPPORTED 4u
#define PWE_EIR_INVALID 5u
#define PWE_CAPABILITY 6u
#define PWE_HANDLE_STALE 7u
#define PWE_CONFLICT 8u
#define PWE_OWNERSHIP_STALE 9u
#define PWE_ABI_MISMATCH 10u
#define PWE_HASH_COLLISION 11u
#define PWE_INTERNAL 255u

/* (const uint8_t* ptr, uint64_t len): 16 bytes. */
typedef struct PweBuffer {
    const uint8_t* ptr;
    uint64_t len;
} PweBuffer;

/* (uint8_t* ptr, uint64_t len): 16 bytes. */
typedef struct PweMutableBuffer {
    uint8_t* ptr;
    uint64_t len;
} PweMutableBuffer;

/* status:u32 detail:u32 byte_offset:u64 message:{ptr,len}: 32 bytes. */
typedef struct PweError {
    PweStatus status;
    uint32_t detail;
    uint64_t byte_offset;
    PweBuffer message; /* UTF-8; len 0 when absent. */
} PweError;

/* kind:u32 index:u32 generation:u32 reserved:u32: 16 bytes. */
typedef struct PweHandle {
    uint32_t kind;
    uint32_t index;
    uint32_t generation;
    uint32_t reserved;
} PweHandle;

/* RFC-0031 component descriptor. Canonical schema values, never native
 * structs; value_align is power-of-two <= 64. */
typedef struct PweComponentDescriptor {
    uint8_t type_id[16]; /* ComponentTypeId */
    uint8_t schema_hash[32]; /* SchemaHash */
    uint32_t abi_major;
    uint32_t flags;
    uint32_t value_size;
    uint32_t value_align;
} PweComponentDescriptor;

/* Function table slots (in RFC-0026 order). Each is an outer-callable
 * function pointer; the first argument is RuntimeApi::user_data.
 * Thread/context: world_get, component_view, resource_get are read-only and
 * reentrant; transaction_begin/submit and handle_release require the caller to
 * serialize access to one world handle. */
typedef PweStatus (*PweWorldGetFn)(void* user, PweBuffer request, PweHandle* out, PweError* err);
typedef PweStatus (*PweComponentViewFn)(void* user, PweHandle entity, PweBuffer component, PweBuffer* out, PweError* err);
typedef PweStatus (*PweResourceGetFn)(void* user, PweBuffer resource, PweBuffer* out, PweError* err);
typedef PweStatus (*PweTransactionBeginFn)(void* user, PweBuffer options, PweBuffer capability, PweHandle* out, PweError* err);
typedef PweStatus (*PweTransactionSubmitFn)(void* user, PweHandle txn, PweBuffer writes, PweBuffer* out, PweError* err);
typedef PweStatus (*PweHandleReleaseFn)(void* user, PweHandle handle, PweError* err);
typedef void (*PweRuntimeFreeFn)(void* user, PweMutableBuffer buffer);

/* u16:u16:u32:ptr + 7 slots = 72 bytes on 64-bit. */
typedef struct PweRuntimeApi {
    uint16_t abi_major;
    uint16_t abi_minor;
    uint32_t size;
    void* user_data;
    PweWorldGetFn world_get;
    PweComponentViewFn component_view;
    PweResourceGetFn resource_get;
    PweTransactionBeginFn transaction_begin;
    PweTransactionSubmitFn transaction_submit;
    PweHandleReleaseFn handle_release;
    PweRuntimeFreeFn runtime_free;
} PweRuntimeApi;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* PWE_ABI_H */